In [1]:
from keras.datasets import mnist

加载数据  
图像被编码为numpy数组，标签是数字数组，取值为0~9

In [2]:
(train_x, train_y), (test_x, test_y) = mnist.load_data()

In [3]:
print(train_x.shape)
print(len(train_x))
print(train_x)

(60000, 28, 28)
60000
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [4]:
print(test_x.shape)
print(len(test_x))
print(test_x)

(10000, 28, 28)
10000
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


构建模型  
两层全链接层  
compile中需要三个参数：损失函数(loss)、优化器(optimizer)、训练和测试过程中需要监控的指标(metric)

In [5]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [6]:
network

归一化

In [7]:
train_x = train_x.reshape((60000, 28*28))
train_x = train_x.astype('float32') / 255

test_x = test_x.reshape((10000, 28*28))
test_x = test_x.astype('float32') / 255

准备标签， 将其变成one-hot形式

In [8]:
from keras.utils import to_categorical
train_y = to_categorical(train_y)
test_y = to_categorical(test_y)

开始训练

In [9]:
network.fit(train_x, train_y, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.4252 - accuracy: 0.8758
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1109 - accuracy: 0.9671
Epoch 3/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0698 - accuracy: 0.9790
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0486 - accuracy: 0.9867
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0368 - accuracy: 0.9887


In [10]:
test_loss, test_acc = network.evaluate(test_x, test_y)
print('test_acc:', test_acc)
print('test_loss:', test_loss)

313/313 [==============================] - 1s 2ms/step - loss: 0.0633 - accuracy: 0.9812
test_acc: 0.9811999797821045
test_loss: 0.06333968043327332


数据存在多维的Numpy数组中，也叫做张量(tensor)  
一般来说，当前所有的机器学习系统都使用张量作为基本数据结构。  
张量的核心在于他是一个数据容器，包含的数据几乎总是数值数据；矩阵为二维张量，张量是矩阵向任意维度的推广。  
张量的维度(dimension)通常叫做轴(axis)。

标量：0D张量，仅含有一个数字的张量叫做标量(scalar)，在Numpy中，一个float32或float64的数字就是一个标量张量(或标量数组)。  
可以使用ndim属性查看Numpy张量的轴的个数。  
标量张量有0个轴(ndim==0)

In [11]:
import numpy as np
x = np.array(12)
print(x)
print(x.ndim)

12
0


向量：1D张量(vector)，一维张量只有一个轴

In [12]:
x = np.array([12, 3, 6, 14, 7])
print(x)
print(x.ndim)

[12  3  6 14  7]
1


矩阵：2D张量，二维张量，矩阵有两个轴

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
